package com.AdiManuLateri3

import android.content.Context
import com.lagradost.cloudstream3.plugins.CloudstreamPlugin
import com.lagradost.cloudstream3.plugins.Plugin
import com.lagradost.api.Log

@CloudstreamPlugin
class Lateri3PlayPlugin: Plugin() {
    override fun load(context: Context) {
        // Mendaftarkan Provider Utama Lateri3Play
        registerMainAPI(Lateri3Play())

        // Mendaftarkan Extractor Tambahan (Diperlukan untuk menyelesaikan link dari berbagai sumber)
        // Daftar ini diambil dari Extractors.kt asli dan disesuaikan
        
        registerExtractorAPI(Animefever())
        registerExtractorAPI(Multimovies())
        registerExtractorAPI(MultimoviesSB())
        registerExtractorAPI(Yipsu())
        registerExtractorAPI(Mwish())
        registerExtractorAPI(TravelR())
        registerExtractorAPI(Playm4u())
        registerExtractorAPI(FileMoon())
        registerExtractorAPI(VCloud())
        registerExtractorAPI(Kwik())
        registerExtractorAPI(VCloudGDirect())
        registerExtractorAPI(Filelions())
        registerExtractorAPI(Snolaxstream())
        registerExtractorAPI(Pixeldra())
        registerExtractorAPI(Graceaddresscommunity())
        registerExtractorAPI(M4ufree())
        registerExtractorAPI(Streamruby())
        registerExtractorAPI(Filelion())
        registerExtractorAPI(dlions())
        registerExtractorAPI(dwish())
        registerExtractorAPI(Embedwish())
        registerExtractorAPI(UqloadsXyz())
        registerExtractorAPI(Uploadever())
        registerExtractorAPI(Netembed())
        registerExtractorAPI(Flaswish())
        registerExtractorAPI(Comedyshow())
        registerExtractorAPI(Ridoo())
        registerExtractorAPI(Streamvid())
        registerExtractorAPI(Embedrise())
        registerExtractorAPI(GDMirrorbot())
        registerExtractorAPI(FilemoonNl())
        registerExtractorAPI(Alions())
        registerExtractorAPI(AllinoneDownloader())
        registerExtractorAPI(Tellygossips())
        registerExtractorAPI(Tvlogy())
        registerExtractorAPI(Gofile())
        registerExtractorAPI(Animezia())
        registerExtractorAPI(Modflix())
        registerExtractorAPI(Sethniceletter())
        registerExtractorAPI(GDFlix())
        registerExtractorAPI(fastdlserver())
        registerExtractorAPI(GDFlix1())
        registerExtractorAPI(GDFlix2())
        registerExtractorAPI(furher())
        registerExtractorAPI(Servertwo())
        registerExtractorAPI(MultimoviesAIO())
        registerExtractorAPI(HubCloud())
        registerExtractorAPI(Driveseed())
        registerExtractorAPI(Driveleech())
        registerExtractorAPI(Embtaku())
        registerExtractorAPI(bulbasaur())
        registerExtractorAPI(Megacloud())
        registerExtractorAPI(Cdnstreame())
        registerExtractorAPI(Rapidplayers())
        registerExtractorAPI(Maxfinishseveral())
        registerExtractorAPI(Pahe())
        registerExtractorAPI(MegaUp())
        registerExtractorAPI(oxxxfile())
        registerExtractorAPI(Hblinks())
        registerExtractorAPI(Videostr())
        registerExtractorAPI(DriveleechPro())
        registerExtractorAPI(DriveleechNet())
        registerExtractorAPI(Molop())
        registerExtractorAPI(showflixupnshare())
        registerExtractorAPI(Rubyvidhub())
        registerExtractorAPI(smoothpre())
        registerExtractorAPI(Akirabox())
        registerExtractorAPI(BuzzServer())
        registerExtractorAPI(FilemoonV2())
        registerExtractorAPI(Hubstreamdad())
        registerExtractorAPI(StreamwishHG())
        registerExtractorAPI(PixelServer())
        registerExtractorAPI(Streameeeeee())
        registerExtractorAPI(Vidora())
        registerExtractorAPI(Fourspromax())
        registerExtractorAPI(XdMoviesExtractor())
        registerExtractorAPI(Hubdrive())
        registerExtractorAPI(Rapidairmax())
        registerExtractorAPI(Rapidshare())
        registerExtractorAPI(HdStream4u())
        registerExtractorAPI(Hubstream())
        registerExtractorAPI(Hubcdnn())
        registerExtractorAPI(HUBCDN())
        registerExtractorAPI(PixelDrainDev())
    }
}
